links = {'main_page': 'some link',
         'login_field': "some link",
         'pass_field': "some link",
         'add_appeal_button': "some link",
         'category_field': "some link",
         'contact_field': "some link",
         'servis_field': "some link",
         'work_field': "some link",
         'project_field': "some link",
         'theme_field': "some link",
         'description_field': "some link",
         'result_field': "some link",
         'worktime_field': "some link",
         'duty_checkbox': "some link",
         'department_field': "some link",
         'save_activity': "some link",
         'somefunc_button': "some link",
         'somefunc_ok_button': "some link"
         }